version: "3.5"
services:
  app:
    build: .
    command: python app.py
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    volumes:
      - type: volume
        source: counter-vol
        target: /code
  redis:
    image: "redis:alpine"

  nginx:
    image: "nginx:alpine"
    ports:
      - "1000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    

volumes:
  counter-vol:
