version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: petclinic_db
    environment:
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=petclinic
    ports:
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mysql

  app:
    build: .
    container_name: petclinic_app
    environment:
      - MYSQL_URL=jdbc:mysql://db:3306/petclinic
      - SPRING_PROFILES_ACTIVE=mysql
    ports:
      - "3007:8080"
    depends_on:
      - db

volumes:
  db-volume:
